# Generated by Django 5.1.4 on 2024-12-25 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayname', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('expires', models.DateTimeField()),
                ('salt', models.BinaryField()),
                ('iv', models.BinaryField()),
                ('ciphertext', models.BinaryField()),
                ('password', models.CharField(blank=True, max_length=255)),
                ('lang', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.language')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.user')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
