# Generated by Django 5.1.4 on 2024-12-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_paste_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='ciphertext',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paste',
            name='iv',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='paste',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paste',
            name='salt',
            field=models.CharField(max_length=24),
        ),
    ]
