# Generated by Django 5.1.4 on 2024-12-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_paste_ciphertext_alter_paste_iv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
