# Generated by Django 5.1.4 on 2024-12-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_paste_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='content',
        ),
    ]
