# Generated by Django 5.1.4 on 2024-12-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_paste_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='iv',
            field=models.CharField(blank=True, default=None, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='paste',
            name='salt',
            field=models.CharField(blank=True, default=None, max_length=24, null=True),
        ),
    ]
