# Generated by Django 5.1.4 on 2024-12-25 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_paste_iv_alter_paste_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='password',
        ),
    ]
