# Generated by Django 5.1.4 on 2025-01-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_remove_paste_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paste",
            name="id",
            field=models.CharField(
                editable=False, max_length=6, primary_key=True, serialize=False
            ),
        ),
    ]
