# Generated by Django 5.1.4 on 2025-01-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_alter_paste_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="paste",
            name="one_time",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paste",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
